### PR TITLE
HTML/CSS Project #7: Using Bootstrap

### PR DESCRIPTION
**Pull request by VanessaAoki**
We build a clone of newsweek.com's homepage using HTML, CSS, and bootstrap. This page works best using the firefox or google chrome browser, assets might look out of place using other browsers or resolutions.

The focus of this branch was to create a responsive website, which should have 3 major breaking points: the first one is supposed to be for mobile displays (max-width: 544px); the second one is for tablets displays (max-width: 768px); and the last one is for laptops/monitors (min-width: 768px);

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @VanessaAoki and @pacyL2K19, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating newsweek.com. Most requirements have been done 👌,  kindly fix the following issues.

[REQUIRED]

- [x] On large screens, it should contain the Newsweek logo at the center of the header.
header original
header

- [x] Fix the bold horizontal line-height below the sub-navigation
bold line


- [x] Use min-width: 1024px for large screens (the debate section should be on the same page with FEATURED STORIES and Top Story)
1024 original



- [x] Remove  .vscode from the GitHub repo and Add it inside .gitignore

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by kelvin8773** [comment]
# Status: Change Required 💅 🕵️ 

Hi, Team,

Thanks for making the effort to finish the project, bravo!! 👍 😮 

However, you guys still need to work harder to make this project get approved.

Currently, I think the major issue of your project is - the website didn't follow the standard responsive breakpoint the original website follow (which also the suggestion from Microverse).

* Big Screen equal to:  >= 1024px
* Medium Screen equal to: >=768px && <= 1023px
* Small Screen equal to: <=767px

[Required]

 - [x] find a way to make your website responsive to the breaking point I mentioned above,

I have captured 3 sizes screenshot for you to help better understand what you should focus on.

## Big Screen
- The second nav bar should align in one line (just like @abredi mention above) when the screen equal to or bigger than 1024px.

Screenshot 2020-11-22 001010

## Medium Screen
Screenshot 2020-11-22 001130

## Small Screen
- When the screen is smaller than 768px
Screenshot 2020-11-22 001224

Once you fix that, please kindly re-submit your project for review, Thanks!

Happy coding! 😄 

Kelvin
PS: Feel free to contact me from Slack or Here if anything unclear. (@Kelvin)

**Comment by pacyL2K19** [comment]
> # Status: Change Required 💅 🕵️
> Hi, Team,
> 
> Thanks for making the effort to finish the project, bravo!! 👍 😮
> 
> However, you guys still need to work harder to make this project get approved.
> 
> Currently, I think the major issue of your project is - the website didn't follow the standard responsive breakpoint the original website follow (which also the suggestion from Microverse).
> 
> * Big Screen equal to:  >= 1024px
> * Medium Screen equal to: >=768px && <= 1023px
> * Small Screen equal to: <=767px
> 
> [Required]
> 
> * [x]  find a way to make your website responsive to the breaking point I mentioned above,
> 
> I have captured 3 sizes screenshot for you to help better understand what you should focus on.
> 
> ## Big Screen
> * The second nav bar should align in one line (just like @abredi mention above) when the screen equal to or bigger than 1024px.
> 
> Screenshot 2020-11-22 001010
> 
> ## Medium Screen
> Screenshot 2020-11-22 001130
> 
> ## Small Screen
> * When the screen is smaller than 768px
>   Screenshot 2020-11-22 001224
> 
> Once you fix that, please kindly re-submit your project for review, Thanks!
> 
> Happy coding! 😄
> 
> Kelvin
> PS: Feel free to contact me from Slack or Here if anything unclear. (@Kelvin)

Thank you for this constructive feedback, we will follow them and contact them if need additional details.

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @pacyL2K19 and @VanessaAoki  ! 👋 👋 👋 

### You have done well so far :clap: However, there are changes required for you to make for the project to be approved. Kindly work on them, this as well and submit them for another code review.

**Recommended**
**Navbar**
- [x] Please remove the horizontal bar beneath the navigation bar.
- [x] Adjust the navbar to be more similar to the actual site's.
- [x] You have a horizontal overflow on desktop screen sizes as well. Please fix that.
**Your's**
Screenshot (9)

**Original**
Screenshot (10)

- [ ] On mobile screens, you have some elements overlapping another.

**Your's**
Screenshot (11)

**Orignal**
Screenshot (12)
 
__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by pacyL2K19** [comment]
> ### Changes Required! ♻️
> Hi @pacyL2K19 and @VanessaAoki ! 👋 👋 👋
> 
> ### You have done well so far 👏 However, there are changes required for you to make for the project to be approved. Kindly work on them, this as well and submit them for another code review.
> **Recommended**
> **Navbar**
> 
> * [x]  Please remove the horizontal bar beneath the navigation bar.
> * [x]  Adjust the navbar to be more similar to the actual site's.
> * [x]  You have a horizontal overflow on desktop screen sizes as well. Please fix that.
>   **Your's**
>   Screenshot (9)
> 
> **Original**
> Screenshot (10)
> 
> * [ ]  On mobile screens, you have some elements overlapping another.
> 
> **Your's**
> Screenshot (11)
> 
> **Orignal**
> Screenshot (12)
> 
> **Kindly make the necessary changes and submit another code review request.**
> _Feel free to reach me on slack for any inquiries about this review._ 😉
> __Grace Tamara Ekunola __
> [GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

Hello dear @Temmarie , We appreciate your helpful feedback, and we've already work on them, but fir the latest feedback we're not sure to understand because when we inspect the page, it looks good for the mobile version so we are a bit confused. (See the screenshot below)
feedback

**Comment by Temmarie** [comment]
Hi @pacyL2K19 , thank you for reaching out to me. It could be an issue with our different screen sizes. I currently cannot see the changes you've made, so please push the current changes you've made.

**Comment by pacyL2K19** [comment]
Hi @Temmarie, I actually pushed the changes
Please take a look

**Comment by Temmarie** [comment]
Hey @pacyL2K19 , I've checked the changes, and it seems to be an issue from my side, as it still remains as I pointed out earlier. I'm not sure why this is happening, but you can ignore this issue.

**Comment by pacyL2K19** [comment]
Thank you for your support

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @pacyL2K19 and @VanessaAoki ! 👋 👋 👋 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by pacyL2K19** [comment]
Thank you so much for your helpful support

**Pull request merged**
